---
- name: Install package
  hosts: all
  become: true
  
  tasks:
    - name: Install user package
      yum:
        name:
          - mc
          - vim
          - tcpdump
        state: latest

- name: Enable forwarding ipv4
  hosts: inetRouter
  become: true

  tasks:
    - name: enable forwarding ipv4
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    
    - name: Disable all rp filter ipv4
      shell: echo "net.ipv4.conf.all.rp_filter = 0" >> /etc/sysctl.conf

    # - name: Disable all rp filter ipv4
    #   shell: echo "net.ipv4.conf.all.arp_filter = 2" >> /etc/sysctl.conf
    
    - name: Disable rp filter ipv4 for eth0
      shell: echo "net.ipv4.conf.eth0.rp_filter = 0" >> /etc/sysctl.conf

    - name: Disable rp filter ipv4 for eth1
      shell: echo "net.ipv4.conf.eth1.rp_filter = 0" >> /etc/sysctl.conf

    - name: Disable rp filter ipv4 for eth2
      shell: echo "net.ipv4.conf.eth2.rp_filter = 0" >> /etc/sysctl.conf

    - name: restrat network
      systemd:
        name: network
        state: restarted


- name: Enable forwarding ipv4
  hosts: centralRouter
  become: true

  tasks:
    - name: Install bridge-utils
      yum:
        name: bridge-utils
        state: latest

    - name: enable forwarding ipv4
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    
    - name: Disable all rp filter ipv4
      shell: echo "net.ipv4.conf.all.rp_filter = 0" >> /etc/sysctl.conf

    # - name: Disable all rp filter ipv4
    #   shell: echo "net.ipv4.conf.all.arp_filter = 2" >> /etc/sysctl.conf
    
    - name: Disable rp filter ipv4 for eth0
      shell: echo "net.ipv4.conf.eth0.rp_filter = 0" >> /etc/sysctl.conf

    - name: Disable rp filter ipv4 for eth1
      shell: echo "net.ipv4.conf.eth1.rp_filter = 0" >> /etc/sysctl.conf

    - name: Disable rp filter ipv4 for eth2
      shell: echo "net.ipv4.conf.eth2.rp_filter = 0" >> /etc/sysctl.conf
    
    - name: Disable rp filter ipv4 for eth3
      shell: echo "net.ipv4.conf.eth3.rp_filter = 0" >> /etc/sysctl.conf

    - name: restrat network
      systemd:
        name: network
        state: restarted